# Generated by Django 3.0.7 on 2020-07-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0008_auto_20200628_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
