# Generated by Django 3.0.7 on 2020-07-05 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0009_auto_20200705_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 17, 41, 40, 130348), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
