# Generated by Django 2.2 on 2020-07-05 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0010_auto_20200705_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 19, 34, 49, 866174), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
