# Generated by Django 3.0.7 on 2020-08-10 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0012_auto_20200724_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistrationshackathon',
            name='noOfMembers',
        ),
        migrations.AddField(
            model_name='eventregistrationshackathon',
            name='nameOfTeam',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='feedbackStatus',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=13),
        ),
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 19, 26, 32, 521998), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
