# Generated by Django 3.0.7 on 2021-03-18 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0013_auto_20200810_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='eSummitRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('eventId', models.IntegerField()),
                ('eventName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('college', models.CharField(default='K. J. Somaiya College of Engineering', max_length=255)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(default='TY', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='eSummitRegistrationHackathon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.IntegerField()),
                ('eventName', models.CharField(max_length=50)),
                ('nameOfTeam', models.CharField(max_length=50)),
                ('leaderEmail', models.EmailField(max_length=254)),
                ('leaderName', models.CharField(max_length=100)),
                ('leaderContact', models.CharField(max_length=50)),
                ('college', models.CharField(default='K. J. Somaiya College of Engineering', max_length=255)),
                ('alternateEmail', models.EmailField(max_length=254)),
                ('alternateContact', models.CharField(max_length=50)),
                ('nameOfMembers', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 14, 47, 33, 50359), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
