# Generated by Django 3.0.7 on 2021-03-18 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0014_auto_20210318_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 14, 53, 40, 324576), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
