# Generated by Django 3.0.7 on 2021-03-18 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_app', '0015_auto_20210318_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESummitMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 18, 17, 0, 26, 161930), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
